// var CITY = prompt("ENTER YOUR CITY");
// if (CITY === "karachi") {
// console.log("Welcome to city of lights")
// }
// var gender = prompt("ENTER YOUR GENDER");
// if (gender === "Male") {
// console.log("Welcome Sir!")
// }
// var gender = prompt("ENTER YOUR GENDER");
// if (gender === "Female") {
// console.log("Welcome Madam!")
// }
// var Message = prompt("Signal color");
// if (Message === "Red") {
//     console.log("Must Stop")
// }
// var Message = prompt("Signal color");
// if (Message === "Yellow") {
//     console.log("Ready To Move")
// }
// var Message = prompt("Signal color");
// if (Message === "Green") {
//     console.log("Move Now")
// }
// var Message = prompt("REMAINING FUEL IN CAR(IN LITERS)");
// if (Message <= "0.25LITER") {
//     console.log("Please refill the fuel in your car")
// }

//  var a = 4;
// if (++a === 5){
// alert("given condition for variable a is true");
// }
//  var b = 82;
// if (b++ === 83){
// alert("given condition for variable b is true");
// }
//  var c = 12;
// if (c++ === 13){
// alert("condition 1 is true");
// }
// if (c === 13){
// alert("condition 2 is true");
// }
// if (++c < 14){
// alert("condition 3 is true");
// }
// if(c === 14){
// alert("condition 4 is true");
// }
//  var materialCost = 20000;
// var laborCost = 2000;
// var totalCost = materialCost + laborCost;
// if (totalCost === laborCost + materialCost){
// alert("The cost equals");
// }
// if (true) {
// alert("True");
// }
// if (false) {
//     alert("false");
// }
//  if("car" < "cat"){
//  alert("car is smaller than cat");
//  }
// var Message = prompt("PERCENTAGE%:");
// if (Message >= "80") {
//     console.log("GRADE:A-ONE                   REMARKS: EXCELLENT")
// }
// var Message = prompt("PERCENTAGE%:");
// if (Message >= "70") {
//     console.log("GRADE:A                       REMARKS: GOOD")
// }
// var Message = prompt("PERCENTAGE%:");
// if (Message >= "60") {
//     console.log("GRADE:B                       REMARKS: YOU NEED TO IMPROVE")
// }
// var Message = prompt("PERCENTAGE%:");
// if (Message <= "60") {
//     console.log("GRADE:FAIL                    REMARKS: SORRY")
// }
// var Message = prompt("rainging from 1 to 10");
// if (Message === "5") {
//     console.log("Bingo! Correct answer")
// } 







// var Message = prompt("TEMPERATURE SHOW");
// if (Message >= "T 40")
//     console.log("It is too hot outside")
// var Message = prompt("TEMPERATURE SHOW");
// if (Message >= "T 30")
//     console.log("The Weathr todat is normal")
// var Message = prompt("TEMPERATURE SHOW");
// if (Message >= "T 20")
//     console.log("Today Weather is cool")
// var Message = prompt("TEMPERATURE SHOW");
// if (Message >= "T 10")
//     console.log("OMG!Today Weather is so cool");
























